server:
  port: 3006
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:./userdb
    username: base
    password: base
    driver-class-name: org.h2.Driver
  flyway:
    url: jdbc:h2:./userdb
    user: base
    password: base
    validate-on-migrate: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect